# NumPy Playground

## Basics

In [3]:
# NumPy is a Python library.
# NumPy is used for working with arrays.
# NumPy is short for "Numerical Python".

import numpy as np
arr = np.array([1, 2, 3, 4, 5], dtype='int16')
print(arr)
print(type(arr))

arr2 = np.array([[8.0, 9.0, 10.0], [6.0, 7.0, 8.0]])
arr2

[1 2 3 4 5]
<class 'numpy.ndarray'>


array([[ 8.,  9., 10.],
       [ 6.,  7.,  8.]])

In [ ]:
# Get dimension
arr.ndim, arr2.ndim

# Get shape
arr.shape
arr2.shape # 2 rows 3 columns

# Get type(memory size)
arr.dtype, arr2.dtype

# Get size (bytes)
arr.itemsize, arr2.itemsize

# Get total size
arr.size, arr2.size # number of elements

arr.size * arr.itemsize, arr2.size * arr2.itemsize # total bytes
arr.nbytes, arr2.nbytes # total bytes

In [ ]:
# Convert data types
arr = np.array([1.1, 2.7, 3.1])
newarr = arr.astype('i') # or (int)
print(newarr)



In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('Number of dimensions :', arr.ndim)

## Accessing/Changing

In [ ]:
a = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
a.shape

# Specific element [r, c]
print(a[1][5])
print(a[1][-1])

# Specific row
print(a[1, :])

# Specific column
print(a[:, 4])

print(a[0, 1:6:2]) # start:end:stepsize
print(a[0:1, 2:4]) # row, column



arr = np.arange(1, 31)
# Reshape into rows with 5 numbers each
arr = arr.reshape(-1, 5)  # -1 automatically calculates the number of rows
arr[2:4, 0:2]

# Diagonal
arr[[0,1,2,3],[1,2,3,4]]
arr.diagonal(offset=1)

# Specific pattern
arr[[0,4,5], 3:]
arr[np.ix_([0,4,5], [3,4])]


# Change
a[1][5] = 20
a[1, 1:4] = 5
a[:, 2] = [1,2]
a

12
12
[ 7  8  9 10 11 12]
[ 5 11]
[2 4 6]
[[3 4]]


array([ 2,  8, 14, 20])

In [ ]:
# 3D Example
arr = np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]])
print(arr)

# Specific element (work outside in)
print(arr[0][1][2]) # first index stands for a block
arr[:,0,:] = [[3,3,4,4]]
arr

## Initialising

In [ ]:
# All 0s matrix
np.zeros(5)
np.zeros((2,3))

# All 1s matrix
np.ones((4,2), dtype='int32')

# Any other number
np.full((2,2), 99) 

# Any other number (full_like)
np.full(arr.shape, 4) # (shape, value)
np.full_like(arr, 4)  # (array, value)



In [ ]:
# Random decimal
np.random.rand(2,4)
np.random.random_sample(arr.shape)

# Random integer
np.random.randint(3,11, size=(3,3))

# Identity matrix
np.identity(4)

# Repeat an array
arr1 = np.array([1,2,3]) # [1 1 1 2 2 2 3 3 3]
r1 = np.repeat(arr1, 3)
print(r1)

arr1 = np.array([[1,2,3]])
r1 = np.repeat(arr1, 3, axis=0)           
print(r1)


## Exercises

In [ ]:
# Ex 1
r1 = np.repeat(np.array([1]), 5)
arr = np.array([[r1,[1, 0, 0, 0, 1],[1, 0, 9, 0, 1], [1, 0, 0, 0, 1], r1]])
arr

output = np.ones((5,5))
zero = np.zeros((3,3))
zero[1,1] = 9
output[1:-1, 1:-1] = zero
output



# Ex 2; 
# • The border is filled with 3s. 
# • The inside (all non-border cells) is filled with 1s. 
# • The very center of the array is 0.

arr = np.full((7,7), 3)
ones = np.ones((5,5))
arr[1:-1, 1:-1] = ones
arr[3,3] = 5
arr


# Ex 3;
# Create a 9×9 array filled with 0s.
	# •	The outer border should be 2s.
	# •	The next inner border should be 1s.
	# •	The center (the 5×5 part) should stay 0.

arr = np.full((9,9), 2)
arr[1:-1, 1:-1] = np.ones((7,7))
arr[2:-2, 2:-2] = np.zeros((5,5))
arr


# Ex 4;
# Create a 7x7 array filled with 0s
# • Cross Pattern (7×7)

arr = np.zeros((7,7))
for i in range(7):
    arr[i, i] = 7
    arr[i, 6 - i] = 7
arr

array([[7., 0., 0., 0., 0., 0., 7.],
       [0., 7., 0., 0., 0., 7., 0.],
       [0., 0., 7., 0., 7., 0., 0.],
       [0., 0., 0., 7., 0., 0., 0.],
       [0., 0., 7., 0., 7., 0., 0.],
       [0., 7., 0., 0., 0., 7., 0.],
       [7., 0., 0., 0., 0., 0., 7.]])

## Miscellaneous

### Other

In [8]:
# Be careful when copying arrays!!

# Wrong way
arr = np.array([1,2,3])
arr2 = arr # arr2 points to the same memory as arr
arr2[0] = 100
arr,arr2

# Right way
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
a, b


(array([1, 2, 3]), array([100,   2,   3]))

### Load Data from File

In [ ]:
file = "/Users/vladyslavshutkevych/Desktop/Tools/NumPy/data.txt"
filedata = np.genfromtxt(file, delimiter=",") # delimiter is separator
filedata.astype('int32') # change file type


### Boolean Masking and Advanced Indexing

In [ ]:
# Find all values that satisfy the condition
filedata > 300
filedata[filedata>300]
np.any(filedata>500, axis=0) # if any true in every column

(filedata > 500) & (filedata < 1000)
~(filedata > 500) & (filedata < 1000) # ~ is a not operator

np.any((filedata>500) & (filedata<1000)) # np.True_



# Index with a list in NumPy
# a = np.array([1,2,3,4,5,6,7,8,9])
# a[[1,2,8]]




## Mathematics

In [ ]:
a = np.array([1,2,3,4])
a + 2 # add 2 to every element

b = np.array([1,0,1,0]) # add to arrays
a+b

np.sin(a)


### Linear Algerba

In [ ]:
# Matrix multiplication
a = np.ones((2,3))
b = np.full((3,2), 2)
np.matmul(a,b)

# Find the determinant
c = np.identity(3)
np.linalg.det(1)

### Statistics

In [ ]:
stats = np.array([[1,2,3], [4,5,6]])
np.min(stats) # general min
np.min(stats, axis=1) # min of each row in 2D
np.min(stats, axis=0) # min of each column in 2D
np.max(stats) # general max
np.sum(stats)


## Reorganising arrays

In [ ]:
# Change the array shape
before = np.array([[1,2,3,4], [5,6,7,8]])
after = before.reshape((8,1))
after = before.reshape((2,2,2))
after

# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1])

# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h2,h1]) # or make a tuple with ((h2,h1))

