In [72]:
# NumPy Playground
# Basics

In [73]:
# NumPy is a Python library.
# NumPy is used for working with arrays.
# NumPy is short for "Numerical Python".

import numpy as np
arr = np.array([1, 2, 3, 4, 5], dtype='int16')
print(arr)
print(type(arr))

arr2 = np.array([[8.0, 9.0, 10.0], [6.0, 7.0, 8.0]])
arr2

[1 2 3 4 5]
<class 'numpy.ndarray'>


array([[ 8.,  9., 10.],
       [ 6.,  7.,  8.]])

In [74]:
# Get dimension
arr.ndim, arr2.ndim

# Get shape
arr.shape
arr2.shape # 2 rows 3 columns

# Get type(memory size)
arr.dtype, arr2.dtype

# Get size (bytes)
arr.itemsize, arr2.itemsize

# Get total size
arr.size, arr2.size # number of elements

arr.size * arr.itemsize, arr2.size * arr2.itemsize # total bytes
arr.nbytes, arr2.nbytes # total bytes

(10, 48)

In [75]:
# Convert data types
arr = np.array([1.1, 2.7, 3.1])
newarr = arr.astype('i') # or (int)
print(newarr)



[1 2 3]


In [76]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('Number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions : 5


In [77]:
# Accessing/Changing

In [78]:
a = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
a.shape

# Specific element [r, c]
print(a[1][5])
print(a[1][-1])

# Specific row
print(a[1, :])

# Specific column
print(a[:, 4])

print(a[0, 1:6:2]) # start:end:stepsize



# Change
a[1][5] = 20
a[1, 1:4] = 5
a[:, 2] = [1,2]

a

12
12
[ 7  8  9 10 11 12]
[ 5 11]
[2 4 6]


array([[ 1,  2,  1,  4,  5,  6],
       [ 7,  5,  2,  5, 11, 20]])

In [79]:
# 3D Example
arr = np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]])
print(arr)

# Specific element (work outside in)
print(arr[0][1][2]) # first index stands for a block
arr[:,0,:] = [[3,3,4,4]]
arr

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
7


array([[[ 3,  3,  4,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [80]:
# Initialising

In [81]:
# All 0s matrix
np.zeros(5)
np.zeros((2,3))

# All 1s matrix
np.ones((4,2), dtype='int32')

# Any other number
np.full((2,2), 99) 

# Any other number (full_like)
np.full(arr.shape, 4) # (shape, value)
np.full_like(arr, 4)  # (array, value)



array([[[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]]])

In [82]:
# Random decimal
np.random.rand(2,4)
np.random.random_sample(arr.shape)

# Random integer
np.random.randint(3,11, size=(3,3))

# Identity matrix
np.identity(4)

# Repeat an array
arr1 = np.array([1,2,3]) # [1 1 1 2 2 2 3 3 3]
r1 = np.repeat(arr1, 3)
print(r1)

arr1 = np.array([[1,2,3]])
r1 = np.repeat(arr1, 3, axis=0)           
print(r1)



[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [83]:
# Exercise

arr1 = np.array([1]) # [1 1 1 2 2 2 3 3 3]
r1 = np.repeat(arr1, 5)
print(r1)

arr = np.array([[[1, 1, 1, 1, 1],[1, 0, 0, 0, 1],[1, 0, 9, 0, 1], [1, 0, 0, 0, 1], [1, 1, 1, 1, 1]]])
arr


[1 1 1 1 1]


array([[[1, 1, 1, 1, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 9, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 1, 1, 1, 1]]])